#ifndef __DAUDIO_BOARD_VER__
#define __DAUDIO_BOARD_VER__

typedef enum daudio_board_ver_data
{
	DAUDIOKK_PLATFORM_WS4=1,
	DAUDIOKK_PLATFORM_WS5,
	DAUDIOKK_PLATFORM_WS3,
	DAUDIOKK_PLATFORM_WS6,
	DAUDIOKK_PLATFORM_WS7,
	DAUDIOKK_PLATFORM_WS8,
	DAUDIOKK_PLATFORM_WS9,
	DAUDIOKK_PLATFORM_WS10,
	DAUDIOKK_PLATFORM_WS11,
} daudio_board_ver_data_t;


typedef enum daudio_ver_bt
{
	DAUDIOKK_BT_VER_1,
	DAUDIOKK_BT_VER_2,
	DAUDIOKK_BT_VER_3,
	DAUDIOKK_BT_VER_4,
	DAUDIOKK_BT_VER_5,
	DAUDIOKK_BT_VER_6,
	DAUDIOKK_BT_VER_7,
	DAUDIOKK_BT_VER_8,
	DAUDIOKK_BT_VER_9,
	DAUDIOKK_BT_RESERVED,
} daudio_ver_bt_t;


typedef enum daudio_ver_data
{
	DAUDIO_VER_LCD = 0,
	DAUDIO_VER_MAIN,
	DAUDIO_VER_HW,
	DAUDIO_VER_BT,
	DAUDIO_VER_MAX
} daudio_ver_data_t;

typedef enum daudio_ver_hw
{
	DAUDIOKK_HW_1ST=1,
	DAUDIOKK_HW_2ND,
	DAUDIOKK_HW_3RD,
	DAUDIOKK_HW_4TH,
	DAUDIOKK_HW_5TH,
	DAUDIOKK_HW_6TH,
	DAUDIOKK_HW_7TH,
	DAUDIOKK_HW_8TH,
	DAUDIOKK_HW_9TH,
} daudio_ver_hw_t;

typedef enum daudio_lcd_versions_oe_int
{
	DAUDIOKK_LCD_OI_10_25_1920_720_INCELL_Si,
	DAUDIOKK_LCD_OI_10_25_1920_720_OGS_TEMP,
	DAUDIOKK_LCD_OI_RESERVED1,
	DAUDIOKK_LCD_OI_RESERVED2,
	DAUDIOKK_LCD_OI_RESERVED3,
	DAUDIOKK_LCD_OI_RESERVED4,
	DAUDIOKK_LCD_OI_RESERVED5,
	DAUDIOKK_LCD_OI_10_25_1920_720_INCELL_LTPS,
	DAUDIOKK_LCD_OI_08_00_1280_720_OGS_Si,
	DAUDIOKK_LCD_OI_RESERVED6,
	DAUDIOKK_LCD_OI_DISCONNECTED,
}daudio_ver_lcd_oi;

typedef enum daudio_lcd_versions_pio_int
{
	DAUDIOKK_LCD_PI_RESERVED1,
	DAUDIOKK_LCD_PI_RESERVED2,
	DAUDIOKK_LCD_PI_RESERVED3,
	DAUDIOKK_LCD_PI_RESERVED4,
	DAUDIOKK_LCD_PI_RESERVED5,
	DAUDIOKK_LCD_PI_10_25_1920_720_PIO_AUO,
	DAUDIOKK_LCD_PI_08_00_800_400_PIO_TRULY,
	DAUDIOKK_LCD_PI_RESERVED6,
	DAUDIOKK_LCD_PI_RESERVED7,
	DAUDIOKK_LCD_PI_RESERVED8,
	DAUDIOKK_LCD_PI_DISCONNECTED,
}daudio_ver_lcd_pi;


typedef enum daudio_lcd_versions_oe_de
{
	DAUDIOKK_LCD_OD_RESERVED1,
	DAUDIOKK_LCD_OD_RESERVED2,
	DAUDIOKK_LCD_OD_RESERVED3,
	DAUDIOKK_LCD_OD_10_25_1920_720_INCELL_Si,
	DAUDIOKK_LCD_OD_12_30_1920_720_INCELL_Si,
	DAUDIOKK_LCD_OD_10_25_1920_720_INCELL_LTPS,
	DAUDIOKK_LCD_OD_08_00_1280_720_OGS_Si,
	DAUDIOKK_LCD_OD_RESERVED4,
	DAUDIOKK_LCD_OD_RESERVED5,
	DAUDIOKK_LCD_OD_RESERVED6,
	DAUDIOKK_LCD_OD_DISCONNECTED,
}daudio_ver_lcd_od;

typedef enum daudio_lcd_versions_pio_de
{
	DAUDIOKK_LCD_PD_RESERVED1,
	DAUDIOKK_LCD_PD_RESERVED2,
	DAUDIOKK_LCD_PD_RESERVED3,
	DAUDIOKK_LCD_PD_RESERVED4,
	DAUDIOKK_LCD_PD_RESERVED5,
	DAUDIOKK_LCD_PD_RESERVED6,
	DAUDIOKK_LCD_PD_RESERVED7,
	DAUDIOKK_LCD_PD_RESERVED8,
	DAUDIOKK_LCD_PD_RESERVED9,
	DAUDIOKK_LCD_PD_RESERVED10,
	DAUDIOKK_LCD_PD_DISCONNECTED,
}daudio_ver_lcd_pd;

void init_daudio_ver(unsigned long *adc);
int adc_valid_check(unsigned long adc, int what, int ver);
unsigned char get_daudio_hw_ver(void);
unsigned char get_daudio_main_ver(void);
unsigned char get_daudio_bt_ver(void);
unsigned char get_daudio_lcd_ver(void);
unsigned long get_daudio_hw_adc(void);
unsigned long get_daudio_main_adc(void);
unsigned long get_daudio_bt_adc(void);
unsigned long get_daudio_lcd_adc(void);
#endif
