#include <daudio_ver.h>

static char *daudio_hw_versions[] =
{
	"DAUDIOKK_HW_1ST",
	"DAUDIOKK_HW_2ND",
	"DAUDIOKK_HW_3RD",
	"DAUDIOKK_HW_4TH",
	"DAUDIOKK_HW_5TH",
	"DAUDIOKK_HW_6TH",
	"DAUDIOKK_HW_7TH",
	"DAUDIOKK_HW_8TH",
	"DAUDIOKK_HW_9TH",
};


//see also platform/tcc893x/include/daudio_ver.h - typedef enum daudio_ver_data
static char *daudio_board_versions[] =
{
	"DAUDIOKK_PLATFORM_WS4",
	"DAUDIOKK_PLATFORM_WS5",
	"DAUDIOKK_PLATFORM_WS3",
	"DAUDIOKK_PLATFORM_WS6",
	"DAUDIOKK_PLATFORM_WS7",
	"DAUDIOKK_PLATFORM_WS8",
	"DAUDIOKK_PLATFORM_WS9",
	"DAUDIOKK_PLATFORM_WS10",
	"DAUDIOKK_PLATFORM_WS11",
};

//see also platform/tcc893x/include/daudio_ver.h - typedef enum daudio_ver_bt
static char *daudio_bt_versions[] =
{
	"DAUDIOKK_BT_VER_1",
	"DAUDIOKK_BT_VER_2",
	"DAUDIOKK_BT_VER_3",
	"DAUDIOKK_BT_VER_4",
	"DAUDIOKK_BT_VER_5",
	"DAUDIOKK_BT_VER_6",
	"DAUDIOKK_BT_VER_7",
	"DAUDIOKK_BT_VER_8",
	"DAUDIOKK_BT_VER_9",
	"DAUDIOKK_BT_RESERVED",
};
static char *daudio_lcd_versions_oe_int[11] =
{
	"DAUDIOKK_LCD_OI_10_25_1920_720_INCELL_Si",
	"DAUDIOKK_LCD_OI_10_25_1920_720_OGS_TEMP",
	"DAUDIOKK_LCD_OI_RESERVED1",
	"DAUDIOKK_LCD_OI_RESERVED2",
	"DAUDIOKK_LCD_OI_RESERVED3",
	"DAUDIOKK_LCD_OI_RESERVED4",
	"DAUDIOKK_LCD_OI_RESERVED5",
	"DAUDIOKK_LCD_OI_10_25_1920_720_INCELL_LTPS",
	"DAUDIOKK_LCD_OI_08_00_1280_720_OGS_Si",
	"DAUDIOKK_LCD_OI_RESERVED6",
	"DAUDIOKK_LCD_OI_DISCONNECTED",
};

static char *daudio_lcd_versions_pio_int[11] =
{
	"DAUDIOKK_LCD_PI_RESERVED1",
	"DAUDIOKK_LCD_PI_RESERVED2",
	"DAUDIOKK_LCD_PI_RESERVED3",
	"DAUDIOKK_LCD_PI_RESERVED4",
	"DAUDIOKK_LCD_PI_RESERVED5",
	"DAUDIOKK_LCD_PI_10_25_1920_720_PIO_AUO",
	"DAUDIOKK_LCD_PI_08_00_800_400_PIO_TRULY",
	"DAUDIOKK_LCD_PI_RESERVED6",
	"DAUDIOKK_LCD_PI_RESERVED7",
	"DAUDIOKK_LCD_PI_RESERVED8",
	"DAUDIOKK_LCD_PI_DISCONNECTED",
};


static char *daudio_lcd_versions_oe_de[11] =
{
	"DAUDIOKK_LCD_OD_RESERVED1",
	"DAUDIOKK_LCD_OD_RESERVED2",
	"DAUDIOKK_LCD_OD_RESERVED3",
	"DAUDIOKK_LCD_OD_10_25_1920_720_INCELL_Si",
	"DAUDIOKK_LCD_OD_12_30_1920_720_INCELL_Si",
	"DAUDIOKK_LCD_OD_10_25_1920_720_INCELL_LTPS",
	"DAUDIOKK_LCD_OD_08_00_1280_720_OGS_Si,
	"DAUDIOKK_LCD_OD_RESERVED4",
	"DAUDIOKK_LCD_OD_RESERVED5",
	"DAUDIOKK_LCD_OD_RESERVED6",
	"DAUDIOKK_LCD_OD_DISCONNECTED",
};

static char *daudio_lcd_versions_pio_de[11] =
{
	"DAUDIOKK_LCD_PD_RESERVED1",
	"DAUDIOKK_LCD_PD_RESERVED2",
	"DAUDIOKK_LCD_PD_RESERVED3",
	"DAUDIOKK_LCD_PD_RESERVED4",
	"DAUDIOKK_LCD_PD_RESERVED5",
	"DAUDIOKK_LCD_PD_RESERVED6",
	"DAUDIOKK_LCD_PD_RESERVED7",
	"DAUDIOKK_LCD_PD_RESERVED8",
	"DAUDIOKK_LCD_PD_RESERVED9",
	"DAUDIOKK_LCD_PD_RESERVED10",
	"DAUDIOKK_LCD_PD_DISCONNECTED",
};

extern unsigned long daudio_borad_revs[3];
